### ISSUE TITLE
gulp_zip with Gradle doesn't work

### ISSUE THREAD

**Issue by troley** [eveoh/room-display#50]
## Expected behaviour

`./gradlew gulp_zip` task performs successfully.

## Actual behaviour

The task fails with an error being thrown. This happens because the current node version.

## Any logs or error output?

```
> Task :gulp_zip FAILED
C:\projects\Java\room-display\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding C:\projects\Java\room-display\node_modules\node-sass\vendor\win32-x64-72\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (C:\projects\Java\room-display\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\projects\Java\room-display\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\projects\Java\room-display\node_modules\gulp-sass\index.js:162:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gulp_zip'.
> Process 'command 'C:\projects\Java\room-display\.nodejs\node-v12.13.1-win-x64\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
4 actionable tasks: 1 executed, 3 up-to-date
```

## Steps to reproduce

1. Use ./gradlew gulp_zip command in a terminal.

## Environment

 - Device: Dell XPS
 - OS: Windows
 - Browser and version: N/A
 - MyTimetable version: room-display latest

## Additional context

When the node version is set to lower version (MyTimetable node version), then the gulp_zip task does work. The problem is the node version set in `build.gradle`.

**Comment by troley** [comment]
Closing because the issue was my own local Node (version 10.16.3) has been used for the task, which eventually fails because of the missing node-sass binding. The required Node version is the one specified in the build.gradle, which is 12.13.1.
